name: Latest blog post workflow
on:
  schedule:
    # Runs at 00:00, only on Sunday and Wednesday.
    - cron: '0 0 * * 0,3'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "7"
          comment_tag_name: "BLOG-POST-LIST"
          feed_list: " https://dev.to/feed/vijay2249,https://medium.com/feed/@vijay2249"
          commit_message: "Updated with latest blog-posts"
