name: Latest blog post workflow
on:
  schedule:
    # At 12:00am on Sunday
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "4"
          feed_list: " https://dev.to/feed/vijay2249,https://medium.com/feed/@vijay2249"
          commit_message: "Updated with latest blog-posts"
